name: waterbus_sdk
description: Flutter plugin of Waterbus. Build video call or online meeting application with SFU model. Supports iOS, Android.
version: 0.0.3
homepage: https://docs.waterbus.tech
publish_to: none

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Utils
  equatable: ^2.0.5
  logger: ^2.0.2+1
  wakelock: ^0.6.2
  replay_kit_launcher: ^1.0.0

  # WebRTC
  sdp_transform: ^0.3.2
  h264_profile_level_id: ^0.2.1
  flutter_webrtc:
    git:
      url: https://github.com/waterbustech/flutter-webrtc.git
      path: "."
      ref: 0.9.45+5

  # Dependency Injection
  get_it: ^7.6.4
  injectable: ^2.3.2

  # Connections
  socket_io_client: ^2.0.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Lints
  flutter_lints: ^3.0.0
  import_sorter: ^4.6.0

  # Code Generator
  injectable_generator: ^2.4.1
  build_runner: ^2.4.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  plugin:
    platforms:
      android:
        package: com.waterbus.waterbus_sdk
        pluginClass: WaterbusSdkPlugin
